# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setEnabled(True)
        mainWindow.resize(1280, 720)
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Lumi.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        mainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slot3 = QtWidgets.QLCDNumber(self.centralwidget)
        self.slot3.setEnabled(True)
        self.slot3.setGeometry(QtCore.QRect(700, 500, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        self.slot3.setFont(font)
        self.slot3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slot3.setDigitCount(2)
        self.slot3.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.slot3.setProperty("intValue", 3)
        self.slot3.setObjectName("slot3")
        self.raceImage = QtWidgets.QGraphicsView(self.centralwidget)
        self.raceImage.setGeometry(QtCore.QRect(550, 160, 191, 241))
        self.raceImage.setObjectName("raceImage")
        self.slot1 = QtWidgets.QLCDNumber(self.centralwidget)
        self.slot1.setEnabled(True)
        self.slot1.setGeometry(QtCore.QRect(540, 500, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        self.slot1.setFont(font)
        self.slot1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slot1.setDigitCount(2)
        self.slot1.setMode(QtWidgets.QLCDNumber.Dec)
        self.slot1.setProperty("intValue", 1)
        self.slot1.setObjectName("slot1")
        self.slot2 = QtWidgets.QLCDNumber(self.centralwidget)
        self.slot2.setEnabled(True)
        self.slot2.setGeometry(QtCore.QRect(620, 420, 61, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(10)
        self.slot2.setFont(font)
        self.slot2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.slot2.setDigitCount(2)
        self.slot2.setProperty("intValue", 2)
        self.slot2.setObjectName("slot2")
        self.rightButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(800, 500, 51, 61))
        self.rightButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/Right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButton.setIcon(icon1)
        self.rightButton.setIconSize(QtCore.QSize(48, 48))
        self.rightButton.setObjectName("rightButton")
        self.leftButton = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(450, 500, 51, 61))
        self.leftButton.setBaseSize(QtCore.QSize(0, 0))
        self.leftButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.leftButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/Left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.leftButton.setIcon(icon2)
        self.leftButton.setIconSize(QtCore.QSize(48, 48))
        self.leftButton.setObjectName("leftButton")
        self.raceDetails = QtWidgets.QTextBrowser(self.centralwidget)
        self.raceDetails.setGeometry(QtCore.QRect(200, 20, 281, 381))
        self.raceDetails.setObjectName("raceDetails")
        self.starterClass = QtWidgets.QTextBrowser(self.centralwidget)
        self.starterClass.setGeometry(QtCore.QRect(810, 20, 281, 381))
        self.starterClass.setObjectName("starterClass")
        self.btnAdvanced = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdvanced.setGeometry(QtCore.QRect(210, 590, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(12)
        self.btnAdvanced.setFont(font)
        self.btnAdvanced.setObjectName("btnAdvanced")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(550, 40, 191, 71))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.raceName = QtWidgets.QTextBrowser(self.centralwidget)
        self.raceName.setGeometry(QtCore.QRect(610, 580, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        self.raceName.setFont(font)
        self.raceName.setObjectName("raceName")
        mainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Character Generator v4"))
        self.rightButton.setShortcut(_translate("mainWindow", "Right"))
        self.leftButton.setShortcut(_translate("mainWindow", "Left"))
        self.btnAdvanced.setText(_translate("mainWindow", "Advanced"))
        self.label.setText(_translate("mainWindow", "Choose Your Race"))
        self.raceName.setHtml(_translate("mainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Monotype Corsiva\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))

